* Basic Properties of Numbers

** Exercise 1

   Prove the following

   1. If $ax = a$ for some number $a \neq 0$, then $x = 1$

     - *Solution*

       \begin{align*}
         ax &= a && \text{Premise} \\
         ax \cdot a^{-1} &= a \cdot a^{-1} && \text{Multiplicative Inverse} \\
         x \cdot a \cdot a^{-1} &= a \cdot a^{-1} && \text{Commutative Law} \\
         x \cdot (a \cdot a^{-1}) &= (a \cdot a^{-1}) && \text{Associative Law} \\
         x \cdot (1) &= (1) && \text{Multiplicative Inverse} \\
         x &= 1
       \end{align*}

   2. $x^2 - y^2 = (x - y)(x + y)$

     - *Solution*

       \begin{align*}
        x^2 - y^2 &= (x - y)(x + y) && \text{Premise} \\
        &= x \cdot (x + y) + (-y)(x + y) && \text{Distributive Law} \\
        &= x \cdot x + x \cdot y + (-y) \cdot x + (-y) \cdot y && \text{Distributive Law} \\
        &= x^2 + x \cdot y + (-x \cdot y) + (-y^2) && \text{Commutative Law} \\
        &= x^2 + (-y^2) && \text{Additive Inverse} \\
        &= x^2 - y^2
       \end{align*}

   3. If $x^2 = y^2$, then $x = y$ or $x = -y$

     - *Solution*

       \begin{align*}
         x^2 &= y^2 && \text{Premise} \\
         x^2 + (-y^2) &= y^2 + (-y^2) && \text{Add $-y^2$ to both sides} \\
         x^2 - y^2 &= 0 && \text{Additive inverse} \\
         (x + y) \cdot (x - y) &= 0 && \text{By previous exercise} \\
       \end{align*}

       Given this last equality, it follows that we must be multiplying
       one of the numbers by 0. Therefore, it follows that either $x+y =
       0$ or $x - y = 0$, and hence:

       \begin{align*}
         x + y &= 0 && \text{Premise of first case} \\
         x + y + (-y) &= 0 + (-y) && \text{Add $-y$ to both sides} \\
         x &= -y && \text{Additive Inverse}
       \end{align*}

       Or:

       \begin{align*}
         x - y &= 0 && \text{Premise of second case} \\
         x - y + y &= 0 + y && \text{Add $-y$ to both sides} \\
         x &= y && \text{Additive Inverse}
       \end{align*}

   4. $x^3 - y^3 = (x - y)(x^2 + xy + y^2)$

     - *Solution*

       \begin{align*}
         x^3 - y^3 &= (x - y)(x^2 + xy + y^2) && \text{Premise} \\
         &= x \cdot (x^2 + xy + y^2) + (-y) \cdot (x^2 + xy + y^2) && \text{Distributive Law}\\
         &= x^3 + x^2y + xy^2 + (-y)\cdot x^2 + (-y)\cdot xy + (-y)\cdot y^2 \\
         &= x^3 + x^2y - x^2y + xy^2 - xy^2 - y^3 && \text{Commutative Law} \\
         &= x^3 - y^3
       \end{align*}

   5. $x^n - y^n = (x - y)(x^{n-1} + x^{n-2}y + \ldots + xy^{n-2} + y^{n-1}$

     - *Solution*

       \begin{align*}
         x^n - y^n &= (x - y)(x^{n-1} + x^{n-2}y + \ldots + xy^{n-2} + y^{n-1} \\
	 &= \sum_{i=1}^{n}(x-y)(x^{n-i}y^{i-1}) \\
	 &= \sum_{i=1}^{n}(x+(-y))(x^{n-i}y^{i-1}) \\
	 &= \sum_{i=1}^{n}xx^{n-i}y^{i-1} +(-y)(x^{n-i}y^{i-1}) \\
	 &= \sum_{i=1}^{n}x^{n-i+1}y^{i-1} -x^{n-i}y^{i-1+1} \\
	 &= \sum_{i=1}^{n}x^{n-i+1}y^{i-1} -x^{n-i}y^{i} \\
	 &= \sum_{i=1}^{n}x^{n-i+1}y^{i-1} + \sum_{i=1}^{n}-x^{n-i}y^{i} \\
	 &= \sum_{i=1}^{n}x^{n-i+1}y^{i-1} + \sum_{i=2}^{n+1}-x^{n-i+1}y^{i-1} \\
	 &= x^n + \sum_{i=2}^{n}x^{n-i+1}y^{i-1} + \sum_{i=2}^{n+1}-x^{n-i+1}y^{i-1} \\
	 &= x^n + \sum_{i=2}^{n}x^{n-i+1}y^{i-1} + \sum_{i=2}^{n}-x^{n-i+1}y^{i-1} + (-y^n) \\
	 &= x^n + \sum_{i=2}^{n}[x^{n-i+1}y^{i-1} + (-x^{n-i+1}y^{i-1})] + (-y^n) \\
	 &= x^n + (-y^n) \\
	 &= x^n -y^n \\
       \end{align*}

** Exercise 2

   What is wrong with the following "proof"? Let $x = y$. Then

   \begin{align*}
     x^2 &= xy \\
     x^2 - y^2 &= xy - y^2 \\
     (x + y)(x - y) &= y(x - y) \\
     x + y &= y \\
     2y &= y \\
     2 &= 1
   \end{align*}

   - *Solution*

     Division by $x - y = 0$.

** Exercise 3

   Prove the following

   1. $\frac{a}{b} = \frac{ac}{bc}$ if $b, c \neq 0$

     - *Solution*

       \begin{align*}
         \frac{a}{b} &= \frac{ac}{bc} \\
	 &= (ac) \cdot (bc)^{-1} \\
	 &= a \cdot (c \cdot c^{-1}) \cdot b^{-1} \\
	 &= a \cdot 1 \cdot b^{-1} \\
	 &= a \cdot b^{-1} \\
	 &= \frac{a}{b}
       \end{align*}

   2. $\frac{a}{b} + \frac{c}{d} = \frac{ad + bc}{bd}$, if $b, d \neq 0$

     - *Solution*

       \begin{align*}
         \frac{a}{b} + \frac{c}{d} &= \frac{ad + bc}{bd} \\
	 &= (ad + bc) \cdot (bd)^{-1} \\
	 &= ad \cdot (bd)^{-1} + bc \cdot (bd)^{-1} \\
	 &= ad \cdot b^{-1} \cdot d^{-1} + bc \cdot b^{-1} \cdot d^{-1} \\
	 &= a \cdot b^{-1} \cdot (d \cdot d^{-1}) + (b \cdot b^{-1}) \cdot c \cdot d^{-1} \\
	 &= a \cdot b^{-1} \cdot 1 + 1 \cdot c \cdot d^{-1} \\
	 &= a \cdot b^{-1} + c \cdot d^{-1} \\
	 &= \frac{a}{b} + \frac{c}{d}
       \end{align*}

   3. $\frac{a}{b} \div \frac{c}{d} = \frac{ad}{bc}$ if $b,c,d \neq 0$

     - *Solution*

       \begin{align*}
         \frac{a}{b} \div \frac{c}{d} &= \frac{ad}{bc} \\
	 &= ad \cdot (bc)^{-1} \\
	 &= a \cdot d \cdot b^{-1} \cdot c^{-1} \\
	 &= a \cdot b^{-1} \cdot d \cdot c^{-1} \\
	 &= a \cdot b^{-1} \div (d \cdot c^{-1})^{-1} \\
	 &= a \cdot b^{-1} \div (d^{-1} \cdot c^{(-1) \cdot (-1)}) \\
	 &= a \cdot b^{-1} \div (d^{-1} \cdot c) \\
	 &= \frac{a}{b} \div \frac{c}{d}
       \end{align*}

** Exercise 4

   Find all numbers $x$ for which

   1. $4 - x < 3 - 2x$

      - *Solution*

	\begin{align*}
          4 - x &< 3 - 2x \\
	  4 - x + 2x &< 3 - 2x + 2x \\
	  4 + x &< 3 \\
	  4 + x + (-4) &< 3 + (-4) \\
	  x &< -1
	\end{align*}

   2. $5 - x^2 < 8$

      - *Solution*

	\begin{align*}
	  5 - x^2 &< 8 \\
	  (-1) \cdot (5 - x^2) &< (-1) \cdot 8 \\
	  -5 + x^2 &> -8 \\
	  -5 + 5 + x^2 &> -8 + 5 \\
	  x^2 &> -3
	\end{align*}

   3. $5 - x^2 < -2$

      - *Solution*

	\begin{align*}
	  5 - x^2 &< -2 \\
	  5 + (-5) - x^2 &< -2 + (-5) \\
	  -x^2 &< -7 \\
	  x^2 &> 7 \\
	  x &> \sqrt{7}
	\end{align*}

   4. $(x - 1)(x - 3) > 0$

      - *Solution*

	There are two cases, either we're multiplying two negative
        numbers or two positive numbers.

	In case they are both positive, it means that $x - 1 > 0$ and
        $x - 3 > 0$, which leads us to conclude that $x > 3$.

	In case they are both negative, it means that $x - 1 < 0$ and
        $x - 3 < 0$, which leads us to conclude taht $x < 1$.

** Exercise 24

   This problem shows that the actual placement of parentheses in a
   sum is irrelevant. The proofs involve "mathematical induction"; if
   you are not familiar with such proofs, but still want to tackle
   this problem, it can be saved until after Chapter 2, where proofs
   by induction are explained.

   Let us agree, for definiteness, that $a_1 + \ldots + a_n$ will
   denote:

   \begin{align*}
     a_1 + (a_2 + (a_3 + \ldots + (a_{n-2} + (a_{n-1} + a_n))) \ldots )
   \end{align*}

   Thus, $a_1 + a_2 + a_3$ denotes $a_1 + (a_2 + a_3)$, and $a_1 +
   a_2 + a_3 + a_4$ denotes $a_1 + (a_2 + (a_3 + a_4))$, etc.

   1. Prove that

      \begin{align*}
        (a_1 + \ldots + a_k) + a_{k+1} = a_1 + \ldots + a_{k+1}
      \end{align*}

      - *Solution*

	Let $k=1$, then we can clearly see that $(a_1) = a_1$, and if
        $k=2$, we have $(a_1) + a_2 = a_1 + a_2$. The premise holds.

	Now, assuming the premise to hold for $k-1$, we have:
   
	\begin{align*}
	  (a_1 + a_2 + \ldots + a_{k-1}) + a_k &= a_1 + \ldots + a_k\\
	\end{align*}

	Therefore,

	\begin{align*}
	  (a_1 + a_2 + \ldots + a_{k-1} + a_k) + a_{k+1} &= (a_1 + \ldots + a_{k-1}) + a_k + a_{k+1}\\
	  &= ((a_1 + \ldots + a_{k-1}) + a_k) + a_{k+1} \\
	  &= a_1 + \ldots + a_k + a_{k+1} \\
	\end{align*}

    2. Prove that if $n \geq k$, then

       \begin{align*}
         (a_1 + \ldots + a_k) + (a_{k+1} + \ldots + a_n) = a_1 + \ldots + a_n
       \end{align*}

       - *Solution*

	 For the case where $n = k$, it's the same case as previous
         exercise. Therefore it's proven.

	 For the cases where $n > k$, we have:

	 \begin{align*}
	   (a_1 + \ldots + a_k) + (a_{k+1} + \ldots + a_n) &= ((a_1 + \ldots + a_k) + a_{k+1}) + (a_{k+2} + \ldots + a_n) \\
	   &= (a_1 + \ldots a_{k+1}) + (a_{k+2} + \ldots + a_n)\\
	 \end{align*}

	 The same argument can be applied for $a_{k+3}, a_{k+4},
         \ldots, a_n$. Therefore

	 \begin{align*}
	   (a_1 + \ldots + a_k) + (a_{k+1} + \ldots + a_n) &= a_1 + \ldots + a_n\\
	 \end{align*}


	 

